apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: entity
spec:
  type: bindings.mysql
  version: v1
  metadata:
    - name: url # Required, define DB connection in DSN format
      value: photoprism:photoprism@tcp(139.198.126.60:3306)/kcore?allowNativePasswords=true
    - name: maxIdleConns
      value: 2
    - name: maxOpenConns
      value: 5